name: Set ingress all
on:
  workflow_dispatch:
jobs:
  set-ingress:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: tranquil-wave-287609
      - name: Update ingress
        run: |
          gcloud run services update meli-postsale \
            --region=southamerica-east1 \
            --ingress=all
